controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
react:
    path: /{req}
    defaults: { _controller: 'App\Controller\StaticController::index' }
    requirements:
        req: ".*"
app_logout:
    path: /api/logout
    methods: GET