# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    project_listener:
      class: App\Listener\ProjectListener
      public: false
      autowire: true
      autoconfigure: true
      arguments: ["@security.token_storage"]
      tags:
        - {name: doctrine.orm.entity_listener}
    report_listener:
      class: App\Listener\ReportListener
      public: false
      autowire: true
      autoconfigure: true
      tags:
        - {name: doctrine.orm.entity_listener}
    connection_listener:
      class: App\Listener\ConnectionListener
      public: false
      autowire: true
      autoconfigure: true
      tags:
        - {name: doctrine.orm.entity_listener}
      arguments: ["@security.token_storage", "@mailer"]
    progress_listener:
      class: App\Listener\ProgressEntryListener
      public: false
      autowire: true
      autoconfigure: true
      tags:
        - {name: doctrine.orm.entity_listener}
      arguments: ["@security.token_storage"]
    user_listener:
      class: App\Listener\User
      public: false
      autowire: true
      autoconfigure: true
      tags:
        - {name: doctrine.orm.entity_listener}
      arguments: ["@security.token_storage", "@mailer"]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter': ~
