name: quest-tracker
recipe: symfony
config:
  webroot: ./backend/public
  database: mysql:8.0
services:
  appserver:
    ssl: false
    build_as_root:
      - curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash
      - apt install symfony-cli
    build:
      - mkdir -p backend/public/app
      - cd backend && composer install
  node:
    type: node:20
    command: cd frontend && npm run dev -- --host 0.0.0.0 --port 80
    port: 80
    build:
      - cd frontend && npm install
tooling:
  npm:
    service: node
    description: runs npm in the frontend directory
    dir: /app/frontend
    cmd: npm
  php:
    dir: /app/backend
proxy:
  appserver:
    - quest-tracker.lndo.site
  node:
    - frontend.quest-tracker.lndo.site
